#============== CS 530 Project 1 ~ MakeFile ============== 

#Project Creators: Bashier Dahman
#Class Information: CS 530, Fall 2020
#Assignment Information: Project #1, HexDump 
#Filename: makefile

################################################################
#          Make File: To Compile Project 1 Assignment          #
#                       Bashier Dahman                         #  
################################################################

# defining our compiler
CC	=	g++

# running g++ and creating the executable file / then running it
all:

	@echo	"Compiling prog1_main.cpp"

	$(CC)	-o	xbd	xbd_main.cpp
	
# this will remove the xbd file to clean up the dir.
clean:
	@echo "Now removing 'xbd' executable"

	rm	xbd	
#######################[ EOF: Makefile ]###################
